name: Deploy to Netlify with Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform  # folder with your .tf files

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Login
        env:
          TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
        run: terraform login -no-color

      - name: Terraform Init
        env:
          TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
        run: terraform init

      - name: Terraform Plan
        env:
          TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
        run: terraform plan

      - name: Terraform Apply
        env:
          TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          TF_VAR_base_name: ${{ secrets.TF_VAR_base_name }}
          TF_VAR_tfc_organization: ${{ secrets.TF_VAR_tfc_organization }}
          TF_VAR_tfc_workspace: ${{ secrets.TF_VAR_tfc_workspace }}
        run: terraform apply -auto-approve
