name: Deploy to Netlify with Terraform

on:
  push:
    branches:
      - main   # triggers on push to main branch

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform   # 👈 points to your folder with .tf files

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6  # match your Terraform version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          TF_VAR_base_name: ${{ secrets.TF_VAR_base_name }}
          TF_VAR_tfc_organization: ${{ secrets.TF_VAR_tfc_organization }}
          TF_VAR_tfc_workspace: ${{ secrets.TF_VAR_tfc_workspace }}
