name: Deploy to Netlify with Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform   # ✅ folder containing your .tf files

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # Authenticate Terraform Cloud
      - name: Configure Terraform Cloud credentials
        run: |
          mkdir -p ~/.terraform.d
          echo '{"credentials":{"app.terraform.io":{"token":"${{ secrets.TF_API_TOKEN }}"}}}' > ~/.terraform.d/credentials.tfrc.json

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        env:
          TF_VAR_netlify_token: ${{ secrets.NETLIFY_TOKEN }}
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        env:
          TF_VAR_netlify_token: ${{ secrets.NETLIFY_TOKEN }}
        run: terraform apply -auto-approve

      - name: Show Netlify URL
        run: |
          SITE_NAME=$(terraform output -raw site_name)
          echo "✅ Your site is live at: https://${SITE_NAME}.netlify.app"
